# Generated by Django 4.1 on 2023-03-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_address_zip"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
